#
# PROGRAM:    assign4
# PROGRAMMER: Alex Boyle
#             z1759628
#

# Compiler variables
CCFLAGS = -Wall

# Rule to link object code files to create executable file
Assign4: Assign4.cc
	g++ -Wall -g -std=c++11 Queue.cc PQueue.cc Process.cc Assign4.cc -o Assign4

clean:
	rm Assign4
