#
# PROGRAM:    assign7
# PROGRAMMER: Alex Boyle
#             z1759628
#

# Compiler variables
CCFLAGS = -Wall

# Rule to link object code files to create executable file
Assign7: Assign7.cc
	g++ -pthread -Wall -g -std=c++11 Assign7.cc -o Assign7

clean:
	rm Assign7
