#
# PROGRAM:    assign6
# PROGRAMMER: Alex Boyle
#             z1759628
#

# Compiler variables
CCFLAGS = -Wall

# Rule to link object code files to create executable file
Assign6: Assign6.cc
	g++ -Wall -g -std=c++11 Assign6.cc -o Assign6

clean:
	rm Assign6