#
# PROGRAM:    assign3
# PROGRAMMER: Alex Boyle
#             z1759628
#

# Compiler variables
CCFLAGS = -Wall

# Rule to link object code files to create executable file
Assign3: assign3.cc
	g++ $(CCFLAGS) assign3.cc -o Assign3

clean:
	rm Assign3
