#
# PROGRAM:    assign2
# PROGRAMMER: Alex Boyle
#             z1759628
#

# Compiler variables
CCFLAGS = -Wall

# Rule to link object code files to create executable file
Assign1: assign1.cc
	g++ $(CCFLAGS) assign1.cc -o Assign1

clean:
	rm Assign1
