#
# PROGRAM:    assign4
# PROGRAMMER: Alex Boyle
#             z1759628
#

# Compiler variables
CCFLAGS = -Wall

# Rule to link object code files to create executable file
Assign4: Assign5.cc
	g++ -pthread -Wall -g -std=c++11 Assign5.cc -o Assign5

clean:
	rm Assign5