#
# PROGRAM:    assign2
# PROGRAMMER: Alex Boyle
#             z1759628
#

# Compiler variables
CCFLAGS = -Wall

# Rule to link object code files to create executable file
Assign2: assign2.cc
	g++ $(CCFLAGS) assign2.cc -o Assign2

clean:
	rm Assign2
